---
- name: publish custom collection
  hosts: builder
  gather_facts: false
  vars_files:
    - "../vaults/{{ env }}.yml"
  tasks:
    - name: include namespace role
      ansible.builtin.include_role:
        name: redhat_cop.ah_configuration.namespace

    - name: include publish role
      ansible.builtin.include_role:
        name: redhat_cop.ah_configuration.publish
...
