---
- name: configure private automation hub after installation
  hosts: all
  gather_facts: false
  connection: local
  vars_files:
    - "../vaults/{{ env }}.yml"
  tasks:
    - name: include repository role
      ansible.builtin.include_role:
        name: redhat_cop.ah_configuration.repository

    - name: include repository sync role
      ansible.builtin.include_role:
        name: redhat_cop.ah_configuration.repository_sync

    - name: include group role
      ansible.builtin.include_role:
        name: redhat_cop.ah_configuration.group
      when: ah_groups | length is not match('0')

    - name: include user role
      ansible.builtin.include_role:
        name: redhat_cop.ah_configuration.user
      when: ah_users | length is not match('0')
...
